### ISSUE TITLE
Add missing JSON mappers

### ISSUE THREAD

**Issue by edewata** [dogtagpki/pki#3567]
There are about 90 classes used in REST API. These classes already have XML mappers using `@XmlRootElement`. We need to make sure that all of them have JSON mappers so the XML mappers can eventually be dropped.

Basically each class needs to have this:
```
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown=true)
public class MyClass {

    public int hashCode() { ... }
    public boolean equals(Object obj) { ... }

    public String toJSON() throws Exception { ... }
    public static MyClass fromJSON(String json) throws Exception { ... }

    public String toString() {
        try {
            return to JSON();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
```

The `toJSON()` and `fromJSON()` methods will be used to validate the mapping in unit tests. If the class doesn't have any XML mapper it's not necessary to add them. See PR #3566 for example.

The classes are located in `base/common` folder and grouped by their packages:

- [x] com.netscape.certsrv.account (ckelley) #3568 
- [x] com.netscape.certsrv.authority (ckelley) #3570 
- [x] com.netscape.certsrv.base (ckelley) #3571 
- [x] com.netscape.certsrv.cert (ckelley) #3582
- [x] com.netscape.certsrv.client (ckelley) #3572 
- [x] com.netscape.certsrv.group (ckelley) #3577 
- [x] com.netscape.certsrv.key (ckelley) #3583 
- [x] com.netscape.certsrv.logging (ckelley) #3579 
- [x] com.netscape.certsrv.profile (ckelley) #3587
- [x] com.netscape.certsrv.property (ckelley) #3580
- [x] com.netscape.certsrv.request (ckelley) #3584 
- [x] com.netscape.certsrv.selftests (ckelley) #3585
- [x] com.netscape.certsrv.system (ckelley) #3591 
- [x] com.netscape.certsrv.tps (ckelley) #3592
- [x] com.netscape.certsrv.user (edewata) #3566 
- [x] org.dogtagpki.common (ckelley) #3576 

Please add your name if you work on a package, and check the box if it's complete. Thanks!

<details>
<summary>List of classes that have the @XmlRootElement annotation</summary>
<p>

```
grep -iR "@XmlRootElement" ~/git/pki | cut -d':' -f1 | cut -d'/' -f5-16 | sort -u
pki/base/common/src/main/java/com/netscape/certsrv/account/Account.java
pki/base/common/src/main/java/com/netscape/certsrv/authority/AuthorityData.java
pki/base/common/src/main/java/com/netscape/certsrv/base/Link.java
pki/base/common/src/main/java/com/netscape/certsrv/base/PKIException.java
pki/base/common/src/main/java/com/netscape/certsrv/base/ResourceMessage.java
pki/base/common/src/main/java/com/netscape/certsrv/cert/CertDataInfo.java
pki/base/common/src/main/java/com/netscape/certsrv/cert/CertDataInfos.java
pki/base/common/src/main/java/com/netscape/certsrv/cert/CertData.java
pki/base/common/src/main/java/com/netscape/certsrv/cert/CertEnrollmentRequest.java
pki/base/common/src/main/java/com/netscape/certsrv/cert/CertRequestInfo.java
pki/base/common/src/main/java/com/netscape/certsrv/cert/CertRequestInfos.java
pki/base/common/src/main/java/com/netscape/certsrv/cert/CertRetrievalRequest.java
pki/base/common/src/main/java/com/netscape/certsrv/cert/CertReviewResponse.java
pki/base/common/src/main/java/com/netscape/certsrv/cert/CertRevokeRequest.java
pki/base/common/src/main/java/com/netscape/certsrv/cert/CertSearchRequest.java
pki/base/common/src/main/java/com/netscape/certsrv/client/ClientConfig.java
pki/base/common/src/main/java/com/netscape/certsrv/group/GroupCollection.java
pki/base/common/src/main/java/com/netscape/certsrv/group/GroupData.java
pki/base/common/src/main/java/com/netscape/certsrv/group/GroupMemberCollection.java
pki/base/common/src/main/java/com/netscape/certsrv/group/GroupMemberData.java
pki/base/common/src/main/java/com/netscape/certsrv/key/AsymKeyGenerationRequest.java
pki/base/common/src/main/java/com/netscape/certsrv/key/KeyArchivalRequest.java
pki/base/common/src/main/java/com/netscape/certsrv/key/KeyData.java
pki/base/common/src/main/java/com/netscape/certsrv/key/KeyInfoCollection.java
pki/base/common/src/main/java/com/netscape/certsrv/key/KeyInfo.java
pki/base/common/src/main/java/com/netscape/certsrv/key/Key.java
pki/base/common/src/main/java/com/netscape/certsrv/key/KeyRecoveryRequest.java
pki/base/common/src/main/java/com/netscape/certsrv/key/KeyRequestInfoCollection.java
pki/base/common/src/main/java/com/netscape/certsrv/key/KeyRequestInfo.java
pki/base/common/src/main/java/com/netscape/certsrv/key/KeyRequestResponse.java
pki/base/common/src/main/java/com/netscape/certsrv/key/SymKeyGenerationRequest.java
pki/base/common/src/main/java/com/netscape/certsrv/logging/ActivityCollection.java
pki/base/common/src/main/java/com/netscape/certsrv/logging/ActivityData.java
pki/base/common/src/main/java/com/netscape/certsrv/logging/AuditConfig.java
pki/base/common/src/main/java/com/netscape/certsrv/logging/AuditFileCollection.java
pki/base/common/src/main/java/com/netscape/certsrv/logging/AuditFile.java
pki/base/common/src/main/java/com/netscape/certsrv/profile/PolicyConstraint.java
pki/base/common/src/main/java/com/netscape/certsrv/profile/PolicyConstraintValue.java
pki/base/common/src/main/java/com/netscape/certsrv/profile/PolicyDefault.java
pki/base/common/src/main/java/com/netscape/certsrv/profile/ProfileAttribute.java
pki/base/common/src/main/java/com/netscape/certsrv/profile/ProfileDataInfo.java
pki/base/common/src/main/java/com/netscape/certsrv/profile/ProfileDataInfos.java
pki/base/common/src/main/java/com/netscape/certsrv/profile/ProfileData.java
pki/base/common/src/main/java/com/netscape/certsrv/profile/ProfileInput.java
pki/base/common/src/main/java/com/netscape/certsrv/profile/ProfileOutput.java
pki/base/common/src/main/java/com/netscape/certsrv/profile/ProfileParameter.java
pki/base/common/src/main/java/com/netscape/certsrv/profile/ProfilePolicy.java
pki/base/common/src/main/java/com/netscape/certsrv/profile/ProfilePolicySet.java
pki/base/common/src/main/java/com/netscape/certsrv/profile/ProfileRetrievalRequest.java
pki/base/common/src/main/java/com/netscape/certsrv/property/Descriptor.java
pki/base/common/src/main/java/com/netscape/certsrv/request/CMSRequestInfo.java
pki/base/common/src/main/java/com/netscape/certsrv/selftests/SelfTestCollection.java
pki/base/common/src/main/java/com/netscape/certsrv/selftests/SelfTestData.java
pki/base/common/src/main/java/com/netscape/certsrv/selftests/SelfTestResult.java
pki/base/common/src/main/java/com/netscape/certsrv/selftests/SelfTestResults.java
pki/base/common/src/main/java/com/netscape/certsrv/system/AdminSetupRequest.java
pki/base/common/src/main/java/com/netscape/certsrv/system/AdminSetupResponse.java
pki/base/common/src/main/java/com/netscape/certsrv/system/CertificateSetupRequest.java
pki/base/common/src/main/java/com/netscape/certsrv/system/CertificateSetupResponse.java
pki/base/common/src/main/java/com/netscape/certsrv/system/DomainInfo.java
pki/base/common/src/main/java/com/netscape/certsrv/system/Feature.java
pki/base/common/src/main/java/com/netscape/certsrv/system/InstallToken.java
pki/base/common/src/main/java/com/netscape/certsrv/system/KRAConnectorInfo.java
pki/base/common/src/main/java/com/netscape/certsrv/system/SecurityDomainHost.java
pki/base/common/src/main/java/com/netscape/certsrv/system/SecurityDomainSubsystem.java
pki/base/common/src/main/java/com/netscape/certsrv/system/SystemCertData.java
pki/base/common/src/main/java/com/netscape/certsrv/system/TPSConnectorCollection.java
pki/base/common/src/main/java/com/netscape/certsrv/system/TPSConnectorData.java
pki/base/common/src/main/java/com/netscape/certsrv/tps/authenticator/AuthenticatorCollection.java
pki/base/common/src/main/java/com/netscape/certsrv/tps/authenticator/AuthenticatorData.java
pki/base/common/src/main/java/com/netscape/certsrv/tps/cert/TPSCertCollection.java
pki/base/common/src/main/java/com/netscape/certsrv/tps/cert/TPSCertData.java
pki/base/common/src/main/java/com/netscape/certsrv/tps/connector/ConnectorCollection.java
pki/base/common/src/main/java/com/netscape/certsrv/tps/connector/ConnectorData.java
pki/base/common/src/main/java/com/netscape/certsrv/tps/profile/ProfileCollection.java
pki/base/common/src/main/java/com/netscape/certsrv/tps/profile/ProfileData.java
pki/base/common/src/main/java/com/netscape/certsrv/tps/profile/ProfileMappingCollection.java
pki/base/common/src/main/java/com/netscape/certsrv/tps/profile/ProfileMappingData.java
pki/base/common/src/main/java/com/netscape/certsrv/tps/token/TokenCollection.java
pki/base/common/src/main/java/com/netscape/certsrv/tps/token/TokenData.java
pki/base/common/src/main/java/com/netscape/certsrv/user/UserCertCollection.java
pki/base/common/src/main/java/com/netscape/certsrv/user/UserCertData.java
pki/base/common/src/main/java/com/netscape/certsrv/user/UserCollection.java
pki/base/common/src/main/java/com/netscape/certsrv/user/UserData.java
pki/base/common/src/main/java/com/netscape/certsrv/user/UserMembershipCollection.java
pki/base/common/src/main/java/com/netscape/certsrv/user/UserMembershipData.java
pki/base/common/src/main/java/org/dogtagpki/common/CAInfo.java
pki/base/common/src/main/java/org/dogtagpki/common/ConfigData.java
pki/base/common/src/main/java/org/dogtagpki/common/Info.java
pki/base/common/src/main/java/org/dogtagpki/common/KRAInfo.java
```

</p>
</details>

**Comment by ckelleyRH** [comment]
@edewata `com.netscape.certsrv.logging` only has one interface in it, `com.netscape.certsrv.logging.ILogSubsystem`, which has no XML annotations. Shall I mark as done, or are you expecting there to be something here which needs annotating?

**Comment by edewata** [comment]
@ckelleyRH Actually this list is for packages in `base/common`. There should be a few of them in `com.netscape.certsrv.logging`. Let me update the description. If a class doesn't have XML mapper yet no need to add it. Thanks!

**Comment by ckelleyRH** [comment]
Ah, there are two packages with the same name, I see!
grep -iR "@XmlRootElement" ~/git/pki | cut -d':' -f1 | sort -u | grep "logging"
/home/ckelley/git/pki/base/common/src/main/java/com/netscape/certsrv/logging/ActivityCollection.java
/home/ckelley/git/pki/base/common/src/main/java/com/netscape/certsrv/logging/ActivityData.java
/home/ckelley/git/pki/base/common/src/main/java/com/netscape/certsrv/logging/AuditConfig.java
/home/ckelley/git/pki/base/common/src/main/java/com/netscape/certsrv/logging/AuditFileCollection.java
/home/ckelley/git/pki/base/common/src/main/java/com/netscape/certsrv/logging/AuditFile.java

**Comment by ckelleyRH** [comment]
@edewata I added a list of classes with the `@XmlRootElement` annotation to the description, in a collapsible form because there are 90 of them!

**Comment by edewata** [comment]
@ckelleyRH Cool, thanks!

**Comment by ckelleyRH** [comment]
All the tags are added, I rebased @edewata's commit to switch to JSON as default and that is going through CI now #3595.

I have attempted to reduce some boilerplate with changes akin to this: #3596 

I am in the process of doing some tidy up changes, adding in some tests, some missing `toString()` methods, etc.

**Comment by ckelleyRH** [comment]
@edewata and myself are discussing various follow up commits to do some tidying up, but the actual issue is now complete so I will close.
