### ISSUE TITLE
Remove XML mappers

### ISSUE THREAD

**Issue by ckelleyRH** [dogtagpki/pki#3606]
Now #3567 is done, we can start removing the XML tags

There are about 90 classes used in REST API. These classes already have XML mappers using `@XmlRootElement`.

The classes are located in `base/common` folder and grouped by their packages:

- [x] com.netscape.certsrv.account (ckelley) #3690  
- [x] com.netscape.certsrv.authority (ckelley) #3611
- [x] com.netscape.certsrv.base (ckelley) #3619
- [x] com.netscape.certsrv.cert (ckelley) #3620 
- [x] com.netscape.certsrv.client (ckelley) #3631 
- [x] com.netscape.certsrv.group (ckelley) #3614
- [x] com.netscape.certsrv.key (ckeley) #3632
- [x] com.netscape.certsrv.logging (ckelley) #3613
- [x] com.netscape.certsrv.profile (ckelley) #3633
- [x] com.netscape.certsrv.property (ckelley) #3603 
- [x] com.netscape.certsrv.request (ckelley) #3634
- [x] com.netscape.certsrv.selftests (ckelley) #3612
- [x] com.netscape.certsrv.system  (ckelley) #3635
- [x] com.netscape.certsrv.tps (ckelley) #3636
- [x] com.netscape.certsrv.user (ckelley) #3637
- [x] org.dogtagpki.common (ckelley) #3610

Please add your name if you work on a package, and check the box if it's complete. Thanks!

<details>
<summary>List of classes that have the @XmlRootElement annotation</summary>
<p>

```
grep -iR "@XmlRootElement" ~/git/pki | cut -d':' -f1 | cut -d'/' -f5-16 | sort -u
pki/base/common/src/main/java/com/netscape/certsrv/account/Account.java
pki/base/common/src/main/java/com/netscape/certsrv/authority/AuthorityData.java
pki/base/common/src/main/java/com/netscape/certsrv/base/Link.java
pki/base/common/src/main/java/com/netscape/certsrv/base/PKIException.java
pki/base/common/src/main/java/com/netscape/certsrv/base/ResourceMessage.java
pki/base/common/src/main/java/com/netscape/certsrv/cert/CertDataInfo.java
pki/base/common/src/main/java/com/netscape/certsrv/cert/CertDataInfos.java
pki/base/common/src/main/java/com/netscape/certsrv/cert/CertData.java
pki/base/common/src/main/java/com/netscape/certsrv/cert/CertEnrollmentRequest.java
pki/base/common/src/main/java/com/netscape/certsrv/cert/CertRequestInfo.java
pki/base/common/src/main/java/com/netscape/certsrv/cert/CertRequestInfos.java
pki/base/common/src/main/java/com/netscape/certsrv/cert/CertRetrievalRequest.java
pki/base/common/src/main/java/com/netscape/certsrv/cert/CertReviewResponse.java
pki/base/common/src/main/java/com/netscape/certsrv/cert/CertRevokeRequest.java
pki/base/common/src/main/java/com/netscape/certsrv/cert/CertSearchRequest.java
pki/base/common/src/main/java/com/netscape/certsrv/client/ClientConfig.java
pki/base/common/src/main/java/com/netscape/certsrv/group/GroupCollection.java
pki/base/common/src/main/java/com/netscape/certsrv/group/GroupData.java
pki/base/common/src/main/java/com/netscape/certsrv/group/GroupMemberCollection.java
pki/base/common/src/main/java/com/netscape/certsrv/group/GroupMemberData.java
pki/base/common/src/main/java/com/netscape/certsrv/key/AsymKeyGenerationRequest.java
pki/base/common/src/main/java/com/netscape/certsrv/key/KeyArchivalRequest.java
pki/base/common/src/main/java/com/netscape/certsrv/key/KeyData.java
pki/base/common/src/main/java/com/netscape/certsrv/key/KeyInfoCollection.java
pki/base/common/src/main/java/com/netscape/certsrv/key/KeyInfo.java
pki/base/common/src/main/java/com/netscape/certsrv/key/Key.java
pki/base/common/src/main/java/com/netscape/certsrv/key/KeyRecoveryRequest.java
pki/base/common/src/main/java/com/netscape/certsrv/key/KeyRequestInfoCollection.java
pki/base/common/src/main/java/com/netscape/certsrv/key/KeyRequestInfo.java
pki/base/common/src/main/java/com/netscape/certsrv/key/KeyRequestResponse.java
pki/base/common/src/main/java/com/netscape/certsrv/key/SymKeyGenerationRequest.java
pki/base/common/src/main/java/com/netscape/certsrv/logging/ActivityCollection.java
pki/base/common/src/main/java/com/netscape/certsrv/logging/ActivityData.java
pki/base/common/src/main/java/com/netscape/certsrv/logging/AuditConfig.java
pki/base/common/src/main/java/com/netscape/certsrv/logging/AuditFileCollection.java
pki/base/common/src/main/java/com/netscape/certsrv/logging/AuditFile.java
pki/base/common/src/main/java/com/netscape/certsrv/profile/PolicyConstraint.java
pki/base/common/src/main/java/com/netscape/certsrv/profile/PolicyConstraintValue.java
pki/base/common/src/main/java/com/netscape/certsrv/profile/PolicyDefault.java
pki/base/common/src/main/java/com/netscape/certsrv/profile/ProfileAttribute.java
pki/base/common/src/main/java/com/netscape/certsrv/profile/ProfileDataInfo.java
pki/base/common/src/main/java/com/netscape/certsrv/profile/ProfileDataInfos.java
pki/base/common/src/main/java/com/netscape/certsrv/profile/ProfileData.java
pki/base/common/src/main/java/com/netscape/certsrv/profile/ProfileInput.java
pki/base/common/src/main/java/com/netscape/certsrv/profile/ProfileOutput.java
pki/base/common/src/main/java/com/netscape/certsrv/profile/ProfileParameter.java
pki/base/common/src/main/java/com/netscape/certsrv/profile/ProfilePolicy.java
pki/base/common/src/main/java/com/netscape/certsrv/profile/ProfilePolicySet.java
pki/base/common/src/main/java/com/netscape/certsrv/profile/ProfileRetrievalRequest.java
pki/base/common/src/main/java/com/netscape/certsrv/property/Descriptor.java
pki/base/common/src/main/java/com/netscape/certsrv/request/CMSRequestInfo.java
pki/base/common/src/main/java/com/netscape/certsrv/selftests/SelfTestCollection.java
pki/base/common/src/main/java/com/netscape/certsrv/selftests/SelfTestData.java
pki/base/common/src/main/java/com/netscape/certsrv/selftests/SelfTestResult.java
pki/base/common/src/main/java/com/netscape/certsrv/selftests/SelfTestResults.java
pki/base/common/src/main/java/com/netscape/certsrv/system/AdminSetupRequest.java
pki/base/common/src/main/java/com/netscape/certsrv/system/AdminSetupResponse.java
pki/base/common/src/main/java/com/netscape/certsrv/system/CertificateSetupRequest.java
pki/base/common/src/main/java/com/netscape/certsrv/system/CertificateSetupResponse.java
pki/base/common/src/main/java/com/netscape/certsrv/system/DomainInfo.java
pki/base/common/src/main/java/com/netscape/certsrv/system/Feature.java
pki/base/common/src/main/java/com/netscape/certsrv/system/InstallToken.java
pki/base/common/src/main/java/com/netscape/certsrv/system/KRAConnectorInfo.java
pki/base/common/src/main/java/com/netscape/certsrv/system/SecurityDomainHost.java
pki/base/common/src/main/java/com/netscape/certsrv/system/SecurityDomainSubsystem.java
pki/base/common/src/main/java/com/netscape/certsrv/system/SystemCertData.java
pki/base/common/src/main/java/com/netscape/certsrv/system/TPSConnectorCollection.java
pki/base/common/src/main/java/com/netscape/certsrv/system/TPSConnectorData.java
pki/base/common/src/main/java/com/netscape/certsrv/tps/authenticator/AuthenticatorCollection.java
pki/base/common/src/main/java/com/netscape/certsrv/tps/authenticator/AuthenticatorData.java
pki/base/common/src/main/java/com/netscape/certsrv/tps/cert/TPSCertCollection.java
pki/base/common/src/main/java/com/netscape/certsrv/tps/cert/TPSCertData.java
pki/base/common/src/main/java/com/netscape/certsrv/tps/connector/ConnectorCollection.java
pki/base/common/src/main/java/com/netscape/certsrv/tps/connector/ConnectorData.java
pki/base/common/src/main/java/com/netscape/certsrv/tps/profile/ProfileCollection.java
pki/base/common/src/main/java/com/netscape/certsrv/tps/profile/ProfileData.java
pki/base/common/src/main/java/com/netscape/certsrv/tps/profile/ProfileMappingCollection.java
pki/base/common/src/main/java/com/netscape/certsrv/tps/profile/ProfileMappingData.java
pki/base/common/src/main/java/com/netscape/certsrv/tps/token/TokenCollection.java
pki/base/common/src/main/java/com/netscape/certsrv/tps/token/TokenData.java
pki/base/common/src/main/java/com/netscape/certsrv/user/UserCertCollection.java
pki/base/common/src/main/java/com/netscape/certsrv/user/UserCertData.java
pki/base/common/src/main/java/com/netscape/certsrv/user/UserCollection.java
pki/base/common/src/main/java/com/netscape/certsrv/user/UserData.java
pki/base/common/src/main/java/com/netscape/certsrv/user/UserMembershipCollection.java
pki/base/common/src/main/java/com/netscape/certsrv/user/UserMembershipData.java
pki/base/common/src/main/java/org/dogtagpki/common/CAInfo.java
pki/base/common/src/main/java/org/dogtagpki/common/ConfigData.java
pki/base/common/src/main/java/org/dogtagpki/common/Info.java
pki/base/common/src/main/java/org/dogtagpki/common/KRAInfo.java
```

</p>
</details>

**Comment by dheerajodha** [comment]
Hello @ckelleyRH, I'm a beginner at this project and I would love to contribute here in order to help and understand this project. As a way to start contributing here, can I take up one of the tasks from this list, more specifically, "com.netscape.certsrv.request"?

**Comment by ckelleyRH** [comment]
Hi @dheerajodha, thanks for dropping in! I'm not sure that this is a good starter issue, it has consequences for other packages/projects that depend on `dogtagpki` - it could be a breaking API change and needs careful testing. I'm new to the project myself, and have been taking guidance from @edewata - perhaps he can suggest a good start point for you :smiley:

**Comment by dheerajodha** [comment]
@ckelleyRH Thanks a lot for your message! 
Oh, I didn't know the implications of these changes, thanks a lot for letting me know
Yes, I would love to know if there are any good first issues. Thanks again! :smile:

**Comment by ckelleyRH** [comment]
Mappers have now been removed.
